# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91532ca2b93ddb1d61c1f1c0a081708f1a1173651cbcd8d87f716cd58515a4eca301e45338ebb1c979b412b4cb9e3bb00d1fadd6002fa088c8118b65e5105e71

test:
  secret_key_base: 40caa45fabf657276ac91a76c64bfc4a9ad0f21bf32c476d39d7b826eb41b998dc2508070a39e102440a3c2081b6f101be6b9fab761e4d177e475772064e6f1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 1a48f2c63c84bc051f9574f970baca9ca9978ea36c624aed08f3ee4b6d0c61648bd6a41d14ac51aca661e4a0fdc22a3fd0bf8b49034689d4d26856382f3e8a8b
